### ISSUE TITLE
JWT auth client

### ISSUE THREAD

**Issue by danilaslynko** [danilaslynko/codi#8]
Implement JWT auth client

**Comment by mtarle** [comment]
Авторизация в codi реализована при помощи jwt token + spring security.  Данные пользователя хранятся в сущности user,  пароль хранится в зашифрованном, алгоритмом BCrypt, виде. 
В регистрации мы на вход принимаем логин и пароль пользователя и вызываем метод сохранения пользователя.
В авторизации мы сначала находим пользователя по логину и паролю, если такой пользователь найден – генерируем ему токен и возвращаем.
